apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-{{ .Release.Name }} # has to match .spec.template.metadata.labels
  replicas: {{ .Values.shlink.replicas }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-{{ .Release.Name }} # has to match .spec.selector.matchLabels
        app.kubernetes.io/name: {{ include "app.name" . }}-{{ .Release.Name }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: {{ .Values.shlink.security.runAsUser }}
        runAsGroup: {{ .Values.shlink.security.runAsGroup }}
      containers:
      - name: {{ include "app.name" . }}-{{ .Release.Name }}
        image: {{ .Values.shlink.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.shlink.port }}
          name: shlink-port
        env:
          - name: TZ
            value: "Europe/Paris"
          - name: PORT
            value: "{{ .Values.shlink.port }}"
          - name: INITIAL_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "app.fullname" . }}-shlink-admin-apikey
                key: admin-apikey
          {{- range $key, $value := .Values.shlink.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}-{{ .Release.Name }}-web
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-{{ .Release.Name }}-web # has to match .spec.template.metadata.labels
  replicas: {{ .Values.shlinkweb.replicas }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-{{ .Release.Name }}-web # has to match .spec.selector.matchLabels
        app.kubernetes.io/name: {{ include "app.name" . }}-{{ .Release.Name }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: {{ .Values.shlinkweb.security.runAsUser }}
        runAsGroup: {{ .Values.shlinkweb.security.runAsGroup }}
      containers:
      - name: {{ include "app.name" . }}-{{ .Release.Name }}
        image: {{ .Values.shlinkweb.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.shlinkweb.port }}
          name: shlinkweb-port
        env:
          - name: TZ
            value: "Europe/Paris"
          - name: PORT
            value: "{{ .Values.shlinkweb.port }}"
          - name: SHLINK_SERVER_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "app.fullname" . }}-shlink-admin-apikey
                key: admin-apikey
          - name: SHLINK_SERVER_URL
            value: "https://{{ .Values.shlink.ingress.host }}"
          {{- range $key, $value := .Values.shlinkweb.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
