apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wireguard
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: wireguard
    port: 51900
    targetPort: 51900
    protocol: UDP
    nodePort: 31900
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dashboard
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: dashboard
    port: 10086
    targetPort: 10086
    protocol: TCP
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}
