apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tcp
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: {{ .Values.portainer.tcpport }}
    targetPort: {{ .Values.portainer.tcpport }}
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.portainer.httpport }}
    targetPort: {{ .Values.portainer.httpport }}
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-https
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: {{ .Values.portainer.httpsport }}
    targetPort: {{ .Values.portainer.httpsport }}
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}
