piholeexporter:
  image: ekofr/pihole-exporter:latest
  replicas: 1
  containerPort: 9617
  exposedPort: 30003

  security:
    runAsUser: 0
    runAsGroup: 0

  environment:

  pihole_hostname: "192.168.2.52"
  pihole_api_token: ""
