apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.immich.apiserver.service.port }}
    targetPort: {{ .Values.immich.apiserver.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-ml
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.immich.machineLearning.service.port }}
    targetPort: {{ .Values.immich.machineLearning.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: machine-learning
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: {{ .Values.immich.redis.service.port }}
    targetPort: {{ .Values.immich.redis.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: {{ .Values.immich.database.service.port }}
    targetPort: {{ .Values.immich.database.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
