tinyauth:
  image: ghcr.io/steveiliop56/tinyauth:v4
  replicas: 1
  port: 3000

  security:
    runAsUser: 0
    runAsGroup: 0

  environment:
    APP_URL: "http://auth.arcanexus.com"

  USERS: 
    - username: admin
      password: $$2a$$10$$UdLYoJ5lgPsC0RKqYH/jMua7zIn0g9kPqWmhYayJYLaZQ/FTmH2/u
