tinyauth:
  image: ghcr.io/steveiliop56/tinyauth:v4
  replicas: 1
  port: 3000

  security:
    runAsUser: 0
    runAsGroup: 0

  environment:
    APP_URL: "http://auth.arcanexus.com"
    APP_TITLE: "Arcanexus Login"
    LOG_LEVEL: "info"

  USERS: 
    - username: admin
      password: $$2a$$10$$UdLYoJ5lgPsC0RKqYH/jMua7zIn0g9kPqWmhYayJYLaZQ/FTmH2/u
    - username: nexus
      password: $$2a$$10$$je72GS/ws0iCOQVlfWZ2Ge5wRim3.ATWq3c7vOnd7SS2kciYCj6I2

  ingress:
    enabled: true
    host: auth.arcanexus.com
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: le-wildcard-issuer