apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-prometheus
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.prometheus.httpport }}
    targetPort: {{ .Values.prometheus.httpport }}
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}-prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pushgateway
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-pushgateway
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.pushgateway.httpport }}
    targetPort: {{ .Values.pushgateway.httpport }}
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}-pushgateway
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-grafana
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.grafana.httpport }}
    targetPort: {{ .Values.grafana.httpport }}
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}-grafana
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-syslog-ng-udp
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-syslog-ng
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: udp
    port: {{ .Values.syslogng.udpport }}
    targetPort: {{ .Values.syslogng.udpport }}
    nodePort: {{ .Values.syslogng.nodePortUdp }}
    protocol: UDP
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}-syslog-ng
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-syslog-ng-tcp
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-syslog-ng
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: tcp
    port: {{ .Values.syslogng.tcpport }}
    targetPort: {{ .Values.syslogng.tcpport }}
    nodePort: {{ .Values.syslogng.nodePortTcp }}
    protocol: TCP
  selector:
    app: {{ include "app.name" . }}-{{ .Release.Name }}-syslog-ng
